export const legalContent = {
  FR: {
    faqTitle: 'FAQ',
    faqItems: [
      { q: 'Quels types de films proposez-vous ?', a: "Trois teintes : l'effet miroir (intimité totale de jour, bloque 99% des UV), la teinte solaire (transparente, réduit la chaleur et les UV) et le blanc mat (intimité totale des deux côtés, idéal salle de bain ou verrière)." },
      { q: "L'effet miroir fonctionne-t-il aussi la nuit ?", a: "De jour, l'effet miroir bloque totalement la vue depuis l'extérieur. La nuit, si votre intérieur est éclairé et qu'il fait sombre dehors, l'effet s'inverse — c'est le fonctionnement normal de ce type de film, à garder en tête selon vos pièces." },
      { q: 'Comment se déroule une demande de devis ?', a: 'Vous nous transmettez vos mesures et quelques photos de vos vitrages pour une première estimation rapide. Si vous le préférez, ou pour les projets plus importants, nous pouvons également nous déplacer chez vous pour confirmer les mesures sur place avant de finaliser le devis.' },
      { q: 'Proposez-vous une visite à domicile ?', a: 'Oui — sur simple demande, ou systématiquement pour les grands chantiers, nous nous déplaçons pour évaluer précisément votre projet.' },
      { q: 'Combien coûte la pose ?', a: 'Le prix dépend du film choisi et de la surface à traiter. Nous établissons un devis personnalisé, sans engagement.' },
      { q: 'Quelle est la durée de vie du film ?', a: "Jusqu'à 10 ans. Nous posons systématiquement à l'intérieur du vitrage, ce qui garantit cette durée de vie optimale." },
      { q: 'Quelle garantie proposez-vous ?', a: '1 an sur la pose.' },
      { q: 'Posez-vous sur tous les types de vitrage ?', a: 'Oui, sur simple, double et triple vitrage.' },
      { q: 'Le film protège-t-il vraiment contre la chaleur et les UV ?', a: "Oui — il bloque jusqu'à 99% des UV et réduit considérablement la chaleur en été, tout en aidant à conserver la chaleur en hiver." },
      { q: 'Le film peut-il protéger mes meubles et mon parquet ?', a: 'Oui, la réduction des UV limite la décoloration des meubles, sols et objets exposés au soleil — le même principe que les films utilisés en muséographie.' },
      { q: 'Dans quelles zones intervenez-vous ?', a: 'Nous nous concentrons actuellement sur Bruxelles et sa périphérie, avec la possibilité de nous déplacer ailleurs en Belgique selon les projets.' },
      { q: 'Qui réalise la pose ?', a: "La pose est assurée par notre installateur partenaire. VitraCare reste votre interlocuteur unique avant et après l'intervention." },
      { q: 'Suis-je engagé après avoir demandé un devis ?', a: 'Non, le devis est gratuit et sans engagement.' },
    ],
    cgmrTitle: 'Conditions générales de mise en relation',
    cgmrSections: [
      { h: '1. Objet', p: ["VitraCare est un service de mise en relation entre les clients et des installateurs partenaires indépendants, spécialisés dans la pose de films pour vitrages. VitraCare n'exécute pas elle-même la prestation de pose."] },
      { h: '2. Rôle de VitraCare', p: ["VitraCare assure la prise de contact, l'établissement d'un devis indicatif, la mise en relation avec l'installateur partenaire, et le suivi de la demande du client."] },
      { h: "3. Rôle de l'installateur partenaire", p: ['La prestation (confirmation des mesures, pose, garantie technique) est réalisée par l\'installateur partenaire (actuellement MK Teint), qui facture directement le client et reste seul responsable de l\'exécution de la prestation.'] },
      { h: '4. Nature du devis', p: ['Le devis transmis par VitraCare est indicatif, établi sur base des informations fournies par le client. Le contrat définitif de prestation est conclu directement entre le client et l\'installateur partenaire, qui peut ajuster le montant après vérification sur place.'] },
      { h: '5. Responsabilité', p: ["VitraCare n'étant pas partie au contrat d'exécution, elle ne peut être tenue responsable des délais, de la qualité de la pose ou de dommages éventuels liés à la prestation elle-même. VitraCare s'engage en revanche sur la qualité de la mise en relation et reste disponible pour tout suivi."] },
      { h: '6. Garantie', p: ["La garantie applicable (1 an sur la pose) est celle offerte par l'installateur partenaire. VitraCare accompagne le client dans le suivi en cas de besoin."] },
      { h: '7. Prix et paiement', p: ["Le prix est fixé d'un commun accord avant intervention. Le paiement s'effectue directement auprès de l'installateur partenaire, selon ses propres modalités."] },
      { h: '8. Droit applicable', p: ['Ces conditions sont régies par le droit belge. Tout litige non résolu à l\'amiable sera porté devant les tribunaux francophones de l\'arrondissement de Bruxelles.'] },
    ],
    mentionsTitle: 'Mentions légales',
    mentionsSections: [
      { h: '1. Éditeur du site', p: ['Le site vitracare.be est édité par Laslo Hase, personne physique.', 'Adresse : Bruxelles, Belgique', 'Email : contact@vitracare.be', "Numéro d'entreprise : non applicable — activité exercée à titre personnel (à mettre à jour dès l'immatriculation d'une structure).", 'Pour nous contacter par téléphone, consultez notre page Contact.'] },
      { h: '2. Directeur de la publication', p: ['Laslo Hase'] },
      { h: '3. Hébergement', p: ['Le site est hébergé par Vercel Inc. (États-Unis) — coordonnées complètes disponibles sur vercel.com/legal.'] },
      { h: '4. Description des services', p: ["Ce site présente les services de teinte et de film pour vitres proposés sous la marque VitraCare. VitraCare agit en tant qu'intermédiaire commercial : la prise de contact, le devis et le suivi client sont assurés par VitraCare, tandis que la pose est réalisée par un installateur partenaire indépendant. Les informations publiées sont données à titre indicatif et peuvent évoluer sans préavis."] },
      { h: '5. Disponibilité du site', p: ['Le site est normalement accessible en permanence. Une interruption pour maintenance technique peut être décidée à tout moment, sans engagement de préavis systématique.'] },
      { h: '6. Propriété intellectuelle', p: ["L'ensemble des contenus présents sur ce site (textes, images, logo, identité visuelle) est la propriété de VitraCare, sauf mention contraire. Toute reproduction, représentation, modification ou exploitation, totale ou partielle, sans autorisation préalable, est interdite."] },
      { h: '7. Limitation de responsabilité', p: ["VitraCare met tout en œuvre pour assurer l'exactitude des informations diffusées sur ce site, sans garantie d'exhaustivité. VitraCare ne pourra être tenue responsable des dommages indirects résultant de l'utilisation du site (bug, incompatibilité technique, interruption de service)."] },
      { h: '8. Droit applicable et juridiction', p: ["Le présent site est soumis au droit belge. Tout litige non résolu à l'amiable dans un délai d'un mois sera porté devant les tribunaux francophones de l'arrondissement de Bruxelles."] },
    ],
    privacyTitle: 'Politique de confidentialité',
    privacySections: [
      { h: '1. Responsable du traitement', p: ['Le responsable du traitement des données collectées sur ce site est Laslo Hase, éditeur de vitracare.be (voir Mentions légales). Pour toute question relative à vos données, vous pouvez nous contacter à l\'adresse contact@vitracare.be.'] },
      { h: '2. Données collectées', p: ['Nous collectons uniquement les données que vous nous transmettez volontairement via nos formulaires :', '— Formulaire de devis : nom, adresse, code postal, email, téléphone.', '— Formulaire de contact : nom, email, message.', "Aucune donnée n'est collectée à votre insu, et nous ne collectons aucune donnée sensible."] },
      { h: '3. Finalité du traitement', p: ['Ces données sont utilisées exclusivement pour répondre à votre demande : établir un devis indicatif, vous recontacter, et le cas échéant vous mettre en relation avec notre installateur partenaire pour l\'exécution de la prestation. Elles ne sont jamais utilisées à des fins de prospection commerciale non sollicitée.'] },
      { h: '4. Base légale', p: ['Le traitement de vos données repose sur les mesures précontractuelles prises à votre demande (article 6.1.b du RGPD) : vous nous transmettez ces informations dans le but d\'obtenir un devis ou une réponse à votre question, en vue d\'une éventuelle prestation.'] },
      { h: '5. Destinataires des données', p: ['Vos données sont reçues par VitraCare (Laslo Hase) par email. Si votre demande implique un devis pour une prestation, elles sont également transmises à notre installateur partenaire (actuellement MK Teint) afin qu\'il puisse établir et exécuter la prestation.', "Le site est hébergé par Vercel Inc., situé aux États-Unis. L'hébergeur peut donc être amené à traiter des données techniques liées à votre visite, dans le cadre de garanties encadrant les transferts de données hors Union européenne.", 'Vos données ne sont jamais vendues ni transmises à des tiers à des fins commerciales.'] },
      { h: '6. Durée de conservation', p: ['Vos données sont conservées le temps nécessaire au traitement de votre demande, et au maximum 3 ans à compter de notre dernier échange, sauf obligation légale de conservation plus longue (notamment en cas de facturation par notre installateur partenaire).'] },
      { h: '7. Cookies', p: ["Ce site n'utilise actuellement aucun cookie de mesure d'audience, de publicité ou de traçage. Il ne dépose aucun cookie non essentiel sur votre appareil. Si cela venait à évoluer (par exemple avec l'ajout d'un outil de statistiques), cette politique sera mise à jour en conséquence et, le cas échéant, votre consentement vous sera demandé au préalable."] },
      { h: '8. Vos droits', p: ["Conformément au RGPD, vous disposez d'un droit d'accès, de rectification, d'effacement et d'opposition concernant vos données personnelles, ainsi que d'un droit à la limitation du traitement et à la portabilité de vos données. Pour exercer ces droits, contactez-nous à contact@vitracare.be. Vous disposez également du droit d'introduire une réclamation auprès de l'Autorité de protection des données belge (APD)."] },
      { h: '9. Sécurité', p: ['Nous prenons des mesures raisonnables pour protéger vos données contre tout accès, modification ou divulgation non autorisés. Les échanges avec nos formulaires transitent par une connexion sécurisée (HTTPS).'] },
      { h: '10. Contact', p: ['Pour toute question relative à cette politique de confidentialité ou à vos données personnelles : contact@vitracare.be.'] },
    ],
  },
  NL: {
    faqTitle: 'Veelgestelde vragen',
    faqItems: [
      { q: 'Welke soorten folie bieden jullie aan?', a: 'Drie tinten: het spiegeleffect (volledige privacy overdag, blokkeert 99% van de UV-stralen), de zonwerende folie (transparant, vermindert warmte en UV) en de matwitte folie (volledige privacy langs beide kanten, ideaal voor badkamer of veranda).' },
      { q: "Werkt het spiegeleffect ook 's nachts?", a: "Overdag blokkeert het spiegeleffect het zicht van buitenaf volledig. 's Nachts, als uw interieur verlicht is en het buiten donker is, keert het effect om — dit is de normale werking van dit type folie, houd hier rekening mee per kamer." },
      { q: 'Hoe verloopt een offerteaanvraag?', a: "U bezorgt ons uw afmetingen en enkele foto's van uw beglazing voor een eerste snelle inschatting. Indien u dit verkiest, of voor grotere projecten, kunnen we ook bij u langsgaan om de afmetingen ter plaatse te bevestigen voordat de offerte wordt afgerond." },
      { q: 'Bieden jullie een huisbezoek aan?', a: 'Ja — op eenvoudig verzoek, of systematisch voor grotere werven, komen we langs om uw project nauwkeurig te evalueren.' },
      { q: 'Hoeveel kost de plaatsing?', a: 'De prijs hangt af van de gekozen folie en de te behandelen oppervlakte. Wij stellen een gepersonaliseerde offerte op, vrijblijvend.' },
      { q: 'Wat is de levensduur van de folie?', a: 'Tot 10 jaar. Wij plaatsen de folie steevast aan de binnenzijde van het glas, wat deze optimale levensduur garandeert.' },
      { q: 'Welke garantie bieden jullie?', a: '1 jaar op de plaatsing.' },
      { q: 'Plaatsen jullie op alle soorten beglazing?', a: 'Ja, op enkel, dubbel en drievoudig glas.' },
      { q: 'Beschermt de folie echt tegen warmte en UV?', a: "Ja — ze blokkeert tot 99% van de UV-stralen en vermindert de warmte in de zomer aanzienlijk, terwijl ze in de winter helpt om warmte te behouden." },
      { q: 'Kan de folie mijn meubels en parket beschermen?', a: 'Ja, de vermindering van UV beperkt de verkleuring van meubels, vloeren en voorwerpen die aan de zon blootgesteld zijn — hetzelfde principe als de folies die in musea worden gebruikt.' },
      { q: 'In welke zones bent u actief?', a: 'We concentreren ons momenteel op Brussel en omgeving, met de mogelijkheid om ons elders in België te verplaatsen naargelang het project.' },
      { q: 'Wie voert de plaatsing uit?', a: 'De plaatsing wordt uitgevoerd door onze partnerinstallateur. VitraCare blijft uw enige aanspreekpunt voor en na de interventie.' },
      { q: 'Ben ik ergens toe verplicht na het aanvragen van een offerte?', a: 'Nee, de offerte is gratis en vrijblijvend.' },
    ],
    cgmrTitle: 'Algemene voorwaarden voor bemiddeling',
    cgmrSections: [
      { h: '1. Voorwerp', p: ['VitraCare is een bemiddelingsdienst tussen klanten en onafhankelijke partnerinstallateurs, gespecialiseerd in het plaatsen van raamfolie. VitraCare voert de plaatsing zelf niet uit.'] },
      { h: '2. Rol van VitraCare', p: ['VitraCare zorgt voor het eerste contact, het opstellen van een indicatieve offerte, de bemiddeling met de partnerinstallateur, en de opvolging van de aanvraag van de klant.'] },
      { h: '3. Rol van de partnerinstallateur', p: ['De dienst (bevestiging van de afmetingen, plaatsing, technische garantie) wordt uitgevoerd door de partnerinstallateur (momenteel MK Teint), die de klant rechtstreeks factureert en als enige verantwoordelijk blijft voor de uitvoering van de dienst.'] },
      { h: '4. Aard van de offerte', p: ['De door VitraCare verstrekte offerte is indicatief en gebaseerd op de door de klant verstrekte informatie. Het definitieve dienstencontract wordt rechtstreeks gesloten tussen de klant en de partnerinstallateur, die het bedrag kan aanpassen na controle ter plaatse.'] },
      { h: '5. Aansprakelijkheid', p: ['Aangezien VitraCare geen partij is bij het uitvoeringscontract, kan zij niet aansprakelijk worden gesteld voor termijnen, de kwaliteit van de plaatsing of eventuele schade verbonden aan de dienst zelf. VitraCare engageert zich daarentegen tot de kwaliteit van de bemiddeling en blijft beschikbaar voor verdere opvolging.'] },
      { h: '6. Garantie', p: ['De toepasselijke garantie (1 jaar op de plaatsing) is deze die door de partnerinstallateur wordt geboden. VitraCare begeleidt de klant indien nodig bij de opvolging.'] },
      { h: '7. Prijs en betaling', p: ['De prijs wordt in onderling overleg vastgelegd vóór de interventie. De betaling gebeurt rechtstreeks aan de partnerinstallateur, volgens diens eigen voorwaarden.'] },
      { h: '8. Toepasselijk recht', p: ['Deze voorwaarden worden beheerst door het Belgisch recht. Elk geschil dat niet minnelijk kan worden opgelost, wordt voorgelegd aan de Franstalige rechtbanken van het arrondissement Brussel.'] },
    ],
    mentionsTitle: 'Wettelijke vermeldingen',
    mentionsSections: [
      { h: '1. Uitgever van de website', p: ['De website vitracare.be wordt uitgegeven door Laslo Hase, natuurlijke persoon.', 'Adres: Brussel, België', 'E-mail: contact@vitracare.be', 'Ondernemingsnummer: niet van toepassing — activiteit uitgeoefend als particulier (bij te werken zodra een structuur wordt geregistreerd).', 'Om ons telefonisch te contacteren, raadpleeg onze Contactpagina.'] },
      { h: '2. Verantwoordelijke uitgever', p: ['Laslo Hase'] },
      { h: '3. Hosting', p: ['De website wordt gehost door Vercel Inc. (Verenigde Staten) — volledige contactgegevens beschikbaar op vercel.com/legal.'] },
      { h: '4. Beschrijving van de diensten', p: ['Deze website presenteert de diensten voor raamfolie en tinten die onder het merk VitraCare worden aangeboden. VitraCare treedt op als commerciële tussenpersoon: het eerste contact, de offerte en de klantopvolging worden door VitraCare verzorgd, terwijl de plaatsing wordt uitgevoerd door een onafhankelijke partnerinstallateur. De gepubliceerde informatie is indicatief en kan zonder voorafgaande kennisgeving wijzigen.'] },
      { h: '5. Beschikbaarheid van de website', p: ['De website is normaal permanent toegankelijk. Een onderbreking voor technisch onderhoud kan op elk moment worden beslist, zonder systematische voorafgaande kennisgeving.'] },
      { h: '6. Intellectuele eigendom', p: ['Alle inhoud op deze website (teksten, afbeeldingen, logo, visuele identiteit) is eigendom van VitraCare, tenzij anders vermeld. Elke reproductie, weergave, wijziging of exploitatie, geheel of gedeeltelijk, zonder voorafgaande toestemming, is verboden.'] },
      { h: '7. Beperking van aansprakelijkheid', p: ['VitraCare doet er alles aan om de juistheid van de op deze website verspreide informatie te waarborgen, zonder garantie op volledigheid. VitraCare kan niet aansprakelijk worden gesteld voor indirecte schade als gevolg van het gebruik van de website (bug, technische incompatibiliteit, onderbreking van de dienst).'] },
      { h: '8. Toepasselijk recht en bevoegdheid', p: ['Deze website is onderworpen aan het Belgisch recht. Elk geschil dat niet binnen een maand minnelijk wordt opgelost, wordt voorgelegd aan de Franstalige rechtbanken van het arrondissement Brussel.'] },
    ],
    privacyTitle: 'Privacybeleid',
    privacySections: [
      { h: '1. Verantwoordelijke voor de verwerking', p: ['De verantwoordelijke voor de verwerking van de op deze website verzamelde gegevens is Laslo Hase, uitgever van vitracare.be (zie Wettelijke vermeldingen). Voor vragen over uw gegevens kunt u ons contacteren via contact@vitracare.be.'] },
      { h: '2. Verzamelde gegevens', p: ['Wij verzamelen uitsluitend de gegevens die u ons vrijwillig verstrekt via onze formulieren:', '— Offerteformulier: naam, adres, postcode, e-mail, telefoon.', '— Contactformulier: naam, e-mail, bericht.', 'Er worden geen gegevens buiten uw medeweten om verzameld, en wij verzamelen geen gevoelige gegevens.'] },
      { h: '3. Doel van de verwerking', p: ['Deze gegevens worden uitsluitend gebruikt om op uw aanvraag te reageren: het opstellen van een indicatieve offerte, contact met u opnemen, en indien nodig u in contact brengen met onze partnerinstallateur voor de uitvoering van de dienst. Ze worden nooit gebruikt voor ongevraagde commerciële prospectie.'] },
      { h: '4. Rechtsgrond', p: ['De verwerking van uw gegevens is gebaseerd op de precontractuele maatregelen die op uw verzoek worden genomen (artikel 6.1.b AVG): u verstrekt ons deze informatie met het doel een offerte of een antwoord op uw vraag te verkrijgen, met het oog op een eventuele dienstverlening.'] },
      { h: '5. Ontvangers van de gegevens', p: ['Uw gegevens worden per e-mail ontvangen door VitraCare (Laslo Hase). Indien uw aanvraag een offerte voor een dienst betreft, worden ze ook doorgestuurd naar onze partnerinstallateur (momenteel MK Teint), zodat deze de dienst kan opstellen en uitvoeren.', 'De website wordt gehost door Vercel Inc., gevestigd in de Verenigde Staten. De hostingprovider kan bijgevolg technische gegevens met betrekking tot uw bezoek verwerken, in het kader van de waarborgen die gelden voor gegevensoverdracht buiten de Europese Unie.', 'Uw gegevens worden nooit verkocht of aan derden doorgegeven voor commerciële doeleinden.'] },
      { h: '6. Bewaartermijn', p: ['Uw gegevens worden bewaard zolang als nodig is voor de verwerking van uw aanvraag, en maximaal 3 jaar na onze laatste uitwisseling, tenzij een langere wettelijke bewaartermijn van toepassing is (met name in geval van facturatie door onze partnerinstallateur).'] },
      { h: '7. Cookies', p: ['Deze website gebruikt momenteel geen enkele cookie voor bezoekersanalyse, reclame of tracking. Er worden geen niet-essentiële cookies op uw toestel geplaatst. Mocht dit veranderen (bijvoorbeeld met de toevoeging van een statistiektool), dan wordt dit beleid dienovereenkomstig bijgewerkt en zal, indien van toepassing, vooraf om uw toestemming worden gevraagd.'] },
      { h: '8. Uw rechten', p: ['Overeenkomstig de AVG heeft u recht op toegang, rectificatie, verwijdering en bezwaar met betrekking tot uw persoonsgegevens, evenals recht op beperking van de verwerking en op gegevensoverdraagbaarheid. Om deze rechten uit te oefenen, contacteer ons via contact@vitracare.be. U heeft ook het recht om een klacht in te dienen bij de Belgische Gegevensbeschermingsautoriteit (GBA).'] },
      { h: '9. Beveiliging', p: ['Wij nemen redelijke maatregelen om uw gegevens te beschermen tegen ongeoorloofde toegang, wijziging of openbaarmaking. Uitwisselingen via onze formulieren verlopen via een beveiligde verbinding (HTTPS).'] },
      { h: '10. Contact', p: ['Voor vragen over dit privacybeleid of uw persoonsgegevens: contact@vitracare.be.'] },
    ],
  },
  EN: {
    faqTitle: 'FAQ',
    faqItems: [
      { q: 'What types of film do you offer?', a: 'Three tints: mirror effect (full daytime privacy, blocks 99% of UV), solar tint (transparent, reduces heat and UV) and matte white (full privacy on both sides, ideal for bathrooms or conservatories).' },
      { q: 'Does the mirror effect also work at night?', a: "During the day, the mirror effect fully blocks the view from outside. At night, if your interior is lit and it's dark outside, the effect reverses — this is normal behaviour for this type of film, worth keeping in mind depending on the room." },
      { q: 'How does a quote request work?', a: 'You send us your measurements and a few photos of your windows for a quick initial estimate. If you prefer, or for larger projects, we can also visit you to confirm the measurements on site before finalising the quote.' },
      { q: 'Do you offer a home visit?', a: 'Yes — on request, or systematically for larger projects, we come to assess your project precisely.' },
      { q: 'How much does installation cost?', a: 'The price depends on the film chosen and the surface to be treated. We draw up a personalised quote, with no obligation.' },
      { q: 'What is the lifespan of the film?', a: 'Up to 10 years. We always install the film on the interior side of the glass, which guarantees this optimal lifespan.' },
      { q: 'What guarantee do you offer?', a: '1 year on the installation.' },
      { q: 'Do you install on all types of glazing?', a: 'Yes, on single, double and triple glazing.' },
      { q: 'Does the film really protect against heat and UV?', a: 'Yes — it blocks up to 99% of UV rays and significantly reduces heat in summer, while helping retain heat in winter.' },
      { q: 'Can the film protect my furniture and flooring?', a: 'Yes, reducing UV limits the fading of furniture, floors and objects exposed to sunlight — the same principle used in museum-grade protective films.' },
      { q: 'Which areas do you cover?', a: 'We currently focus on Brussels and its periphery, with the possibility of travelling elsewhere in Belgium depending on the project.' },
      { q: 'Who carries out the installation?', a: 'The installation is carried out by our partner installer. VitraCare remains your single point of contact before and after the work.' },
      { q: 'Am I committed to anything after requesting a quote?', a: 'No, the quote is free and comes with no obligation.' },
    ],
    cgmrTitle: 'Terms of introduction service',
    cgmrSections: [
      { h: '1. Purpose', p: ['VitraCare is a matchmaking service connecting clients with independent partner installers specialised in window film installation. VitraCare does not carry out the installation itself.'] },
      { h: "2. VitraCare's role", p: ["VitraCare handles the initial contact, draws up an indicative quote, connects the client with the partner installer, and follows up on the client's request."] },
      { h: '3. Role of the partner installer', p: ['The service (confirming measurements, installation, technical warranty) is carried out by the partner installer (currently MK Teint), who invoices the client directly and remains solely responsible for the execution of the service.'] },
      { h: '4. Nature of the quote', p: ['The quote provided by VitraCare is indicative, based on the information supplied by the client. The final service contract is concluded directly between the client and the partner installer, who may adjust the amount after an on-site inspection.'] },
      { h: '5. Liability', p: ['As VitraCare is not a party to the execution contract, it cannot be held liable for delays, the quality of the installation, or any damage related to the service itself. VitraCare does however commit to the quality of the matchmaking service and remains available for any follow-up.'] },
      { h: '6. Warranty', p: ['The applicable warranty (1 year on the installation) is the one offered by the partner installer. VitraCare assists the client with follow-up if needed.'] },
      { h: '7. Price and payment', p: ['The price is agreed jointly before the work takes place. Payment is made directly to the partner installer, according to their own terms.'] },
      { h: '8. Applicable law', p: ['These terms are governed by Belgian law. Any dispute not resolved amicably will be brought before the French-speaking courts of the Brussels judicial district.'] },
    ],
    mentionsTitle: 'Legal notice',
    mentionsSections: [
      { h: '1. Website publisher', p: ['The website vitracare.be is published by Laslo Hase, private individual.', 'Address: Brussels, Belgium', 'Email: contact@vitracare.be', 'Company number: not applicable — activity carried out as a private individual (to be updated once a company is registered).', 'To contact us by phone, please see our Contact page.'] },
      { h: '2. Publication director', p: ['Laslo Hase'] },
      { h: '3. Hosting', p: ['The website is hosted by Vercel Inc. (United States) — full contact details available at vercel.com/legal.'] },
      { h: '4. Description of services', p: ['This website presents the window tinting and film services offered under the VitraCare brand. VitraCare acts as a commercial intermediary: the initial contact, quote and client follow-up are handled by VitraCare, while installation is carried out by an independent partner installer. The information published is provided for guidance and may change without notice.'] },
      { h: '5. Site availability', p: ['The site is normally accessible at all times. An interruption for technical maintenance may be decided at any time, without systematic prior notice.'] },
      { h: '6. Intellectual property', p: ['All content on this website (text, images, logo, visual identity) is the property of VitraCare, unless otherwise stated. Any reproduction, representation, modification or use, in whole or in part, without prior authorisation, is prohibited.'] },
      { h: '7. Limitation of liability', p: ['VitraCare makes every effort to ensure the accuracy of the information published on this website, without guaranteeing its completeness. VitraCare cannot be held liable for indirect damages resulting from use of the site (bugs, technical incompatibility, service interruption).'] },
      { h: '8. Applicable law and jurisdiction', p: ['This website is subject to Belgian law. Any dispute not resolved amicably within one month will be brought before the French-speaking courts of the Brussels judicial district.'] },
    ],
    privacyTitle: 'Privacy policy',
    privacySections: [
      { h: '1. Data controller', p: ['The controller responsible for processing data collected on this website is Laslo Hase, publisher of vitracare.be (see Legal notice). For any questions regarding your data, you can contact us at contact@vitracare.be.'] },
      { h: '2. Data collected', p: ['We only collect the data you voluntarily provide through our forms:', '— Quote form: name, address, postal code, email, phone.', '— Contact form: name, email, message.', 'No data is collected without your knowledge, and we do not collect any sensitive data.'] },
      { h: '3. Purpose of processing', p: ['This data is used exclusively to respond to your request: to draw up an indicative quote, to contact you, and where relevant to put you in touch with our partner installer for the execution of the service. It is never used for unsolicited commercial prospecting.'] },
      { h: '4. Legal basis', p: ['The processing of your data is based on pre-contractual measures taken at your request (Article 6.1.b GDPR): you provide us with this information in order to obtain a quote or a response to your question, with a view to a possible service.'] },
      { h: '5. Data recipients', p: ['Your data is received by VitraCare (Laslo Hase) by email. If your request involves a quote for a service, it is also forwarded to our partner installer (currently MK Teint) so they can prepare and carry out the service.', 'The site is hosted by Vercel Inc., located in the United States. The host may therefore process technical data related to your visit, within the framework of safeguards governing data transfers outside the European Union.', 'Your data is never sold or passed on to third parties for commercial purposes.'] },
      { h: '6. Retention period', p: ['Your data is kept for as long as necessary to process your request, and for a maximum of 3 years from our last exchange, unless a longer legal retention period applies (particularly in the case of invoicing by our partner installer).'] },
      { h: '7. Cookies', p: ['This website currently does not use any cookies for audience measurement, advertising or tracking. It does not place any non-essential cookies on your device. Should this change (for example with the addition of a statistics tool), this policy will be updated accordingly and, where applicable, your consent will be requested beforehand.'] },
      { h: '8. Your rights', p: ['In accordance with the GDPR, you have the right to access, rectify, erase and object to the processing of your personal data, as well as the right to restrict processing and to data portability. To exercise these rights, contact us at contact@vitracare.be. You also have the right to lodge a complaint with the Belgian Data Protection Authority (APD/GBA).'] },
      { h: '9. Security', p: ['We take reasonable measures to protect your data against unauthorised access, alteration or disclosure. Exchanges through our forms take place over a secure connection (HTTPS).'] },
      { h: '10. Contact', p: ['For any questions regarding this privacy policy or your personal data: contact@vitracare.be.'] },
    ],
  },
};
